version: '3.8'
services:
  emi-saas-customer-backend:
    container_name: emi-saas-customer-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    environment:
      - DB_HOST:saas-db.caleavytxajq.us-east-1.rds.amazonaws.com
      - DB_NAME:emi_saas_db
      - DB_USERNAME:admin
      - DB_PASSWORD:admin123
      - DB_PORT:3306
    ports:
      - 3001:3001
    volumes:
      - .:/user/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
