// Sign Up
export const SIGN_UP_IDENTIFIER_IS_DUPLICATAED =
  'SIGN_UP_IDENTIFIER_IS_DUPLICATAED';
export const SIGN_UP_IDENTIFIER_IS_NOT_EXIST =
  'SIGN_UP_IDENTIFIER_IS_NOT_EXIST';
export const SIGN_UP_CODE_INCORRECT = 'SIGN_UP_CODE_INCORRECT';
export const SIGN_UP_CODE_IS_EXPIRED = 'SIGN_UP_CODE_IS_EXPIRED';
export const USER_IS_ALREADY_REGISTERED = 'USER_IS_ALREADY_REGISTERED';

// Sign In
export const PASSWORD_INCORRECT = 'PASSWORD_INCORRECT';

// Get Me
export const USER_IS_NOT_EXIST = 'USER_IS_NOT_EXIST';
export const UNAUTHORIZED = 'UNAUTHORIZED';
