/**
 * 0 - CREATE
 * 1 - UPDATE
 */
export enum SaveEmailType {
  CREATE,
  UPDATE,
}

/**
 * 0 - VERIFF_NOTIFICATION
 * 1 - CREATE_KYC_CERTIFICATE_SUCCESS_NOTIFICATION
 */
export enum EmailTypes {
  VERIFF_NOTIFICATION,
  CREATE_KYC_CERTIFICATE_SUCCESS_NOTIFICATION,
}
