on:
  push:
    branches: [ main ]

name: Exoid Backend Deployment Pipeline

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        host : ${{ secrets.HOST_DNS }}
        username : ${{ secrets.USERNAME }}
        script: |
            cd /home/${{ secrets.USERNAME }}/ExoidBackend
            sudo git pull
            sudo docker-compose down
            sudo docker system prune --force
            sudo docker-compose up --build -d 
